import assert from "node:assert/strict";
import { describe, test } from "node:test";

import { RemediationItemSchema } from "../src/debt/debt-finding.mjs";
import { clusterSignalsEnriched } from "../src/debt/cluster.mjs";
import { shapeFinding } from "../src/debt/shape.mjs";

const uuid = (n) => `00000000-0000-4000-a000-${String(n).padStart(12, "0")}`;

/**
 * Thin adapter: convert a remediation_item artifact into a format that can be
 * passed to the existing PR-based execution loop (dev-loop skill).
 *
 * In practice, this would create a GitHub issue with structured body and
 * acceptance criteria, then hand it to `dev-loop --target issue:<n>`.
 * This adapter validates the shape and produces a GitHub-issue-compatible
 * payload without actually creating an issue.
 *
 * @param {object} remediationItem — RemediationItemSchema-valid artifact
 * @returns {{ title: string, body: string, labels: string[] }}
 */
function remediationToIssuePayload(remediationItem) {
  const parsed = RemediationItemSchema.parse(remediationItem);
  const acSection = parsed.acceptanceCriteria
    .map((ac, i) => `${i + 1}. ${ac}`)
    .join("\n");

  const body = [
    `## Remediation Item`,
    ``,
    `**Finding ID:** ${parsed.findingId}`,
    `**Score:** ${parsed.score}`,
    `**Primary file:** ${parsed.primaryFilePath || "N/A"}`,
    ``,
    `### Description`,
    parsed.description,
    ``,
    `### Acceptance Criteria`,
    acSection,
    ``,
    `### Source`,
    `Generated by debt pipeline from ${parsed.signalIds.length} signal(s).`,
  ].join("\n");

  return {
    title: parsed.title,
    body,
    labels: ["debt", "remediation"],
  };
}

describe("debt integration seam", () => {
  test("remediation_item passes schema validation", () => {
    const item = {
      kind: "remediation_item",
      findingId: "550e8400-e29b-41d4-a716-446655440000",
      title: "Fix spaghetti in auth",
      description: "Refactor login handler.",
      acceptanceCriteria: ["Extract strategies", "No regression"],
      score: 85,
      primaryFilePath: "src/auth/login.mjs",
      filePaths: ["src/auth/login.mjs"],
      signalIds: [uuid(1), uuid(2)],
      sourceType: "debt_pipeline",
      createdAt: "2024-06-03T12:00:00Z",
      updatedAt: "2024-06-03T12:00:00Z",
    };
    const result = RemediationItemSchema.safeParse(item);
    assert.equal(result.success, true);
  });

  test("remediation_item converts to issue payload without errors", () => {
    const item = {
      kind: "remediation_item",
      findingId: "550e8400-e29b-41d4-a716-446655440000",
      title: "Fix spaghetti in auth",
      description: "Refactor login handler to use strategy pattern.",
      acceptanceCriteria: [
        "Extract auth strategies into separate functions",
        "No regression in login test suite",
        "Maintain >= 90% coverage",
      ],
      score: 85,
      primaryFilePath: "src/auth/login.mjs",
      filePaths: ["src/auth/login.mjs"],
      signalIds: [uuid(1), uuid(2)],
      sourceType: "debt_pipeline",
      createdAt: "2024-06-03T12:00:00Z",
      updatedAt: "2024-06-03T12:00:00Z",
    };

    const payload = remediationToIssuePayload(item);
    assert.ok(payload.title.includes("spaghetti"));
    assert.ok(payload.body.includes("## Remediation Item"));
    assert.ok(payload.body.includes("### Acceptance Criteria"));
    assert.ok(payload.body.includes("1. Extract auth strategies"));
    assert.deepEqual(payload.labels, ["debt", "remediation"]);
  });

  test("full pipeline: signals → finding → remediation_item → issue payload", () => {
    // Create synthetic signals
    const signals = [
      {
        id: uuid(1), sourceType: "pr_review_deep_persona",
        signalKind: "spaghetti_branching", severityHint: "high",
        location: { filePath: "src/auth/login.mjs" },
        timestamp: "2024-06-03T12:00:00Z", confidence: 0.9,
      },
      {
        id: uuid(2), sourceType: "pr_review_deep_persona",
        signalKind: "spaghetti_branching", severityHint: "high",
        location: { filePath: "src/auth/login.mjs" },
        timestamp: "2024-06-03T12:00:00Z", confidence: 0.9,
      },
    ];

    // Cluster
    const findings = clusterSignalsEnriched(signals);
    assert.equal(findings.length, 1);

    // Shape
    const { outcome, artifact } = shapeFinding(findings[0]);
    assert.equal(outcome, "remediation_item");
    assert.ok(artifact);

    // Validate schema
    const parsed = RemediationItemSchema.safeParse(artifact);
    assert.equal(parsed.success, true);

    // Convert to issue payload
    const payload = remediationToIssuePayload(artifact);
    assert.ok(payload.title);
    assert.ok(payload.body.includes("spaghetti"));
    assert.ok(payload.labels.includes("debt"));
  });

  test("invalid remediation_item is rejected by schema before conversion", () => {
    const badItem = {
      kind: "remediation_item",
      findingId: "not-a-uuid",
      title: "",
      description: "",
      acceptanceCriteria: [],
      score: 150,
      signalIds: [],
      createdAt: "bad-date",
      updatedAt: "bad-date",
    };
    assert.equal(RemediationItemSchema.safeParse(badItem).success, false);
  });
});
